apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplejavaapp
  labels:
    app: samplejavaapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplejavaapp
  template:
    metadata:
      labels:
        app: samplejavaapp
    spec:
      containers:
      - name: samplejavaapp
        image: sahubibh/samplejavaapp
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: samplejavaapp-svc
spec:
  type: LoadBalancer
  selector:
    app: samplejavaapp
  ports:
  - prot: 8080
    targetport: 8888
    
